baseURL = 'https://dáithí.ie/'
locale = 'en-uk'
title = 'Destroy my soul (and all that I am) Blog'
theme = 'hugo-theme-nostyleplease'

[params]
colorScheme = "dark"
enableSearch = true
showReadingTime = true


